fix: small fixes + dry-run

diff --git a/.github/workflows/bot.yml b/.github/workflows/bot.yml
--- a/.github/workflows/bot.yml
+++ b/.github/workflows/bot.yml
@@ -20,7 +20,7 @@ on:
   workflow_dispatch:
     inputs:
       pull-request-list:
-        description: "PR(s) to process : specify 'all' or a comma separated list of PR numbers, e.g. '42,1337,7890'"
+        description: "PR(s) to process: specify 'all' or a comma separated list of PR numbers, e.g. '42,1337,7890'"
         required: true
         default: all
         type: string
@@ -50,7 +50,7 @@ jobs:
             # If the input is 'all', create a matrix with every open PRs
             if [ '${{ inputs.pull-request-list }}' = 'all' ]; then
               pr_list=`gh pr list --state 'open' --repo '${{ github.repository }}' --json 'number' --template '{{$first := true}}{{range .}}{{if $first}}{{$first = false}}{{else}}, {{end}}{{"\""}}{{.number}}{{"\""}}{{end}}'`
-              [ -z "$pr_list" ] && echo 'Error : no opened PR found' >&2 && exit 1
+              [ -z "$pr_list" ] && echo 'Error: no opened PR found' >&2 && exit 1
               echo "pr-numbers=[$pr_list]" >> "$GITHUB_OUTPUT"
             # If the input is not 'all', test for each number in the comma separated
             # list if the associated PR is opened, then add it to the matrix
@@ -61,7 +61,7 @@ jobs:
               for number in $pr_list; do
                 trimed=`echo "$number" | xargs`
                 pr_state=`gh pr view "$trimed" --repo '${{ github.repository }}' --json 'state' --template '{{.state}}' 2> /dev/null`
-                [ "$pr_state" != 'OPEN' ] && echo "Error : PR with number <$trimed> is not opened" >&2 && exit 1
+                [ "$pr_state" != 'OPEN' ] && echo "Error: PR with number <$trimed> is not opened" >&2 && exit 1
               done
               echo "pr-numbers=[$pr_list]" >> "$GITHUB_OUTPUT"
             fi
@@ -72,7 +72,7 @@ jobs:
           elif [ '${{ github.event_name }}' = 'pull_request' ]; then
             echo 'pr-numbers=["${{ github.event.pull_request.number }}"]' >> "$GITHUB_OUTPUT"
           else
-            echo 'Error : unknown event ${{ github.event_name }}' >&2 && exit 1
+            echo 'Error: unknown event ${{ github.event_name }}' >&2 && exit 1
           fi
 
   # This job processes each pull request in the matrix individually while ensuring
